In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
data1 = pd.read_csv("./results/[K=1]MAC_data.csv")
data2 = pd.read_csv("./results/[K=2]MAC_data.csv")
data = pd.concat([data1, data2], axis=0)
data.shape

(24000, 14)

In [5]:
data = data.sort_values(by=['seed', 'n', 'alpha'])
data.head()

,Unnamed: 0,seed,N,n,alpha,M,K,OMR,CMR(0.1),ELC(0.1),CMR(0.05),ELC(0.05),CMR(0.01),ELC(0.01)
0,0,0,2000,1000,0.25,72,1,0.0090,0.001028,0.0275,0.000000,0.033000,0.000000,0.0485
0,0,0,2000,1000,0.25,72,2,0.0230,0.006670,0.1240,0.100500,0.000605,0.001712,0.1735
500,500,0,2000,1000,0.50,72,1,0.0065,0.001017,0.0165,0.000511,0.022000,0.000000,0.0305
1000,1000,0,2000,1000,0.50,72,2,0.0125,0.002154,0.0915,0.071500,0.000578,0.000550,0.1355
1000,1000,0,2000,1000,0.75,72,1,0.0080,0.001017,0.0165,0.000000,0.021500,0.000000,0.0290

In [6]:
MAC = data.loc[:, ["n", "alpha", "M", "K", "seed", "OMR", 
                    "CMR(0.1)", "CMR(0.05)", "CMR(0.01)", 
                    "ELC(0.1)", "ELC(0.05)", "ELC(0.01)"]]
MAC_tab = MAC.groupby(['K', 'n', 'alpha']).mean()

In [7]:
MAC_tab["OMR"] = MAC_tab["OMR"] * 100
MAC_tab["CMR(0.1)"] = MAC_tab["CMR(0.1)"] * 100
MAC_tab["ELC(0.1)"] = MAC_tab["ELC(0.1)"] * 100
MAC_tab["CMR(0.05)"] = MAC_tab["CMR(0.05)"] * 100
MAC_tab["ELC(0.05)"] = MAC_tab["ELC(0.05)"] * 100
MAC_tab["CMR(0.01)"] = MAC_tab["CMR(0.01)"] * 100
MAC_tab["ELC(0.01)"] = MAC_tab["ELC(0.01)"] * 100
MAC_tab

                  M   seed      OMR  CMR(0.1)  CMR(0.05)  CMR(0.01)  ELC(0.1)  \
K n    alpha
1 1000 0.25    72.0  499.5  0.76380  0.104939   0.051174   0.010026   2.32835
       0.50    72.0  499.5  0.54105  0.067997   0.029846   0.004539   1.68340
       0.75    72.0  499.5  0.43650  0.056734   0.024738   0.003488   1.39040
       1.00    72.0  499.5  0.37735  0.046457   0.020773   0.003428   1.20335
  2500 0.25   159.0  499.5  0.32638  0.040718   0.018058   0.002812   1.02644
       0.50   159.0  499.5  0.23088  0.028125   0.012255   0.001946   0.73084
       0.75   159.0  499.5  0.18796  0.022939   0.010522   0.001800   0.60104
       1.00   159.0  499.5  0.16610  0.020266   0.009403   0.001595   0.52060
  5000 0.25   293.0  499.5  0.16980  0.021012   0.009998   0.001676   0.53735
       0.50   293.0  499.5  0.12014  0.015068   0.006301   0.000977   0.38497
       0.75   293.0  499.5  0.09872  0.012008   0.005362   0.000945   0.31422
       1.00   293.0  499.5  0.08636  0.010098   0.004556   0.000784   0.27369
2 1000 0.25    72.0  499.5  1.65110  0.252281   9.410100   0.123039  11.98165
       0.50    72.0  499.5  1.14145  0.150838   7.080150   0.068244   9.02900
       0.75    72.0  499.5  0.94375  0.123839   5.842800   0.056478   7.48585
       1.00    72.0  499.5  0.80330  0.100058   5.104400   0.043165   6.51695
  2500 0.25   159.0  499.5  0.68580  0.085709   4.284340   0.038946   5.46576
       0.50   159.0  499.5  0.47994  0.056681   3.069380   0.025148   3.92720
       0.75   159.0  499.5  0.39020  0.047248   2.509880   0.021577   3.21324
       1.00   159.0  499.5  0.33724  0.040274   2.174440   0.017752   2.78386
  5000 0.25   293.0  499.5  0.35133  0.041055   2.251540   0.018041   2.88371
       0.50   293.0  499.5  0.25126  0.030631   1.599660   0.013998   2.05114
       0.75   293.0  499.5  0.20254  0.024227   1.310210   0.010994   1.67599
       1.00   293.0  499.5  0.17577  0.020878   1.137170   0.009346   1.45517

              ELC(0.05)  ELC(0.01)
K n    alpha
1 1000 0.25    2.982650    4.23750
       0.50    2.167550    3.07200
       0.75    1.789100    2.53160
       1.00    1.548150    2.19465
  2500 0.25    1.315780    1.86130
       0.50    0.938320    1.32904
       0.75    0.772600    1.08998
       1.00    0.665000    0.94310
  5000 0.25    0.688890    0.97525
       0.50    0.495040    0.69509
       0.75    0.404020    0.56851
       1.00    0.349550    0.49179
2 1000 0.25    0.024944   16.64270
       0.50    0.013573   12.59355
       0.75    0.009164   10.47300
       1.00    0.008092    9.13315
  2500 0.25    0.006867    7.67556
       0.50    0.004316    5.51884
       0.75    0.003268    4.52840
       1.00    0.002935    3.93118
  5000 0.25    0.002939    4.06427
       0.50    0.002070    2.89530
       0.75    0.001895    2.37022
       1.00    0.001286    2.05670

In [8]:
MAC_tab = pd.DataFrame(MAC_tab)
MAC_tab = MAC_tab.reset_index()
MAC_tab

,K,n,alpha,M,seed,OMR,CMR(0.1),CMR(0.05),CMR(0.01),ELC(0.1),ELC(0.05),ELC(0.01)
0,1,1000,0.25,72.0,499.5,0.76380,0.104939,0.051174,0.010026,2.32835,2.982650,4.23750
1,1,1000,0.50,72.0,499.5,0.54105,0.067997,0.029846,0.004539,1.68340,2.167550,3.07200
2,1,1000,0.75,72.0,499.5,0.43650,0.056734,0.024738,0.003488,1.39040,1.789100,2.53160
3,1,1000,1.00,72.0,499.5,0.37735,0.046457,0.020773,0.003428,1.20335,1.548150,2.19465
4,1,2500,0.25,159.0,499.5,0.32638,0.040718,0.018058,0.002812,1.02644,1.315780,1.86130
5,1,2500,0.50,159.0,499.5,0.23088,0.028125,0.012255,0.001946,0.73084,0.938320,1.32904
6,1,2500,0.75,159.0,499.5,0.18796,0.022939,0.010522,0.001800,0.60104,0.772600,1.08998
7,1,2500,1.00,159.0,499.5,0.16610,0.020266,0.009403,0.001595,0.52060,0.665000,0.94310
8,1,5000,0.25,293.0,499.5,0.16980,0.021012,0.009998,0.001676,0.53735,0.688890,0.97525
9,1,5000,0.50,293.0,499.5,0.12014,0.015068,0.006301,0.000977,0.38497,0.495040,0.69509
10,1,5000,0.75,293.0,499.5,0.09872,0.012008,0.005362,0.000945,0.31422,0.404020,0.56851
11,1,5000,1.00,293.0,499.5,0.08636,0.010098,0.004556,0.000784,0.27369,0.349550,0.49179
12,2,1000,0.25,72.0,499.5,1.65110,0.252281,9.410100,0.123039,11.98165,0.024944,16.64270
13,2,1000,0.50,72.0,499.5,1.14145,0.150838,7.080150,0.068244,9.02900,0.013573,12.59355
14,2,1000,0.75,72.0,499.5,0.94375,0.123839,5.842800,0.056478,7.48585,0.009164,10.47300
15,2,1000,1.00,72.0,499.5,0.80330,0.100058,5.104400,0.043165,6.51695,0.008092,9.13315
16,2,2500,0.25,159.0,499.5,0.68580,0.085709,4.284340,0.038946,5.46576,0.006867,7.67556
17,2,2500,0.50,159.0,499.5,0.47994,0.056681,3.069380,0.025148,3.92720,0.004316,5.51884
18,2,2500,0.75,159.0,499.5,0.39020,0.047248,2.509880,0.021577,3.21324,0.003268,4.52840
19,2,2500,1.00,159.0,499.5,0.33724,0.040274,2.174440,0.017752,2.78386,0.002935,3.93118
20,2,5000,0.25,293.0,499.5,0.35133,0.041055,2.251540,0.018041,2.88371,0.002939,4.06427
21,2,5000,0.50,293.0,499.5,0.25126,0.030631,1.599660,0.013998,2.05114,0.002070,2.89530
22,2,5000,0.75,293.0,499.5,0.20254,0.024227,1.310210,0.010994,1.67599,0.001895,2.37022
23,2,5000,1.00,293.0,499.5,0.17577,0.020878,1.137170,0.009346,1.45517,0.001286,2.05670

In [9]:
MAC_tab.to_csv("./results/MAC_tab.csv")